-- Migration 004: Añadir columnas adicionales a VISITAS para sincronizar con el formulario de registro
BEGIN;
ALTER TABLE IF EXISTS VISITAS
  ADD COLUMN IF NOT EXISTS sexo VARCHAR(20),
  ADD COLUMN IF NOT EXISTS edad INTEGER,
  ADD COLUMN IF NOT EXISTS municipio VARCHAR(255),
  ADD COLUMN IF NOT EXISTS sector VARCHAR(100),
  ADD COLUMN IF NOT EXISTS cargo VARCHAR(255),
  ADD COLUMN IF NOT EXISTS funcion VARCHAR(50),
  ADD COLUMN IF NOT EXISTS actividad_economica VARCHAR(255),
  ADD COLUMN IF NOT EXISTS funcionario VARCHAR(255);
COMMIT;
